version: '3'
services:
  db:
    container_name: pg_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gokemon
      POSTGRES_PASSWORD: wesh123
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server-tier
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gokemon_server
    restart: always
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "wesh123"
      DB_HOST: "db:5432"
      DB_NAME: "gokemon"
    ports:
      - "8080:8080"
    networks:
      - server-tier
    depends_on:
      - db
volumes:
  db-data:
    driver: local
networks:
  server-tier:
  client-tier: