version: '3'
services:
  db:
    container_name: pg_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gokemon
      POSTGRES_PASSWORD: wesh123
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server-tier
volumes:
  db-data:
    driver: local
networks:
  server-tier:
  client-tier: